config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :apis do
    member do
      get 'events/:event_id' => 'apis#event'
    end
  end

  namespace :api do
    get '' => 'mock#index'
    get ':uuid/' => 'mock#catch_all', defaults: {format: 'json'}
    post ':uuid/' => 'mock#catch_all', defaults: {format: 'json'}
    put ':uuid/' => 'mock#catch_all', defaults: {format: 'json'}
    delete ':uuid/' => 'mock#catch_all', defaults: {format: 'json'}
    patch ':uuid/' => 'mock#catch_all', defaults: {format: 'json'}
  end
end

app/models/api.rb
class Api < ActiveRecord::Base
  has_many :events

  before_destroy :destroy_events

  def self.clear_apis_inactive_than(age)
    time = (Time.now - age).to_s

    Api.where('updated_at < ?', time.in_time_zone('UTC')).each do |api|
      api.destroy_events
    end

    Api.delete_all(['updated_at < ?', time.in_time_zone('UTC')])
  end

  def self.clear_apis_older_than(age)
    time = (Time.now - age).to_s

    Api.where('created_at < ?', time.in_time_zone('UTC')).each do |api|
      api.destroy_events
    end

    Api.delete_all(['created_at < ?', time.in_time_zone('UTC')])
  end

  def destroy_events
    self.events.each do |event|
      event.destroy_properties
    end
    Event.where(api_id: self.id).delete_all()
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :api

  has_many :properties

  before_destroy :destroy_properties

  def params
    Property.where(event: self, name: 'action_dispatch.request.parameters').first.value
  end

  def self.clear_events_older_than(age)
    time = (Time.now - age).to_s

    Event.where('created_at < ?', time.in_time_zone('UTC')).each do |event|
      event.destroy_properties
    end

    Event.delete_all(['created_at < ?', time.in_time_zone('UTC')])
  end

  def destroy_properties
    Property.where(event_id: self.id).delete_all()
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :event
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ::ApplicationController
end

app/controllers/api/mock_controller.rb
class Api::MockController < ApplicationController
  protect_from_forgery with: :null_session

  respond_to :json

  def index
  end

  def catch_all
    api = Api.where(uuid: params[:uuid]).first
    api.touch

    event = Event.new

    result = {}
    result[:method] = request.method
    result[:body] = request.body
    event.method = request.method
    event.body = request.body.read
    event.api = api

    event.save

    env = {}
    request.env.map { |key, value| env[key] = value.to_s }
    result[:env] = env

    headers = {}
    request.headers.each { |key, value| headers[key] = value.to_s }
    result[:headers] = headers

    Property.bulk_insert do |worker|
      env.each do |name, value|
        worker.add({name: name, source: 'env', value: value, event_id: event.id})
      end
      headers.each do |name, value|
        worker.add({name: name, source: 'header', value: value, event_id: event.id})
      end
    end

    result[:params] = params
    if api.nil?
      result[:api_name] = 'Not found'
    else
      result[:api_name] = api.name
    end
    respond_with result, location: apis_url
  end
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  def index
    @apis = Api.all
  end

  def show
    @api = Api.find(params[:id])
  end

  def new
    @api = Api.new
  end

  def edit
    @api = Api.find(params[:id])
  end

  def create
    @api = Api.new(api_params)
    @api.uuid = SecureRandom.uuid

    if @api.save
      redirect_to @api
    else
      render 'new'
    end
  end

  def update
    @api = Api.find(params[:id])

    if @api.update(api_params)
      redirect_to @api
    else
      render 'edit'
    end
  end

  def destroy
    @api = Api.find(params[:id])
    @api.destroy

    redirect_to apis_path
  end

  def event
    @event = Event.find(params[:event_id])
  end

  private

  def api_params
    params.require(:api).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_raven_context

  private

  def set_raven_context
    Raven.user_context(id: session[:current_user_id]) # or anything else in session
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apis/_form.html.erb
<%= form_for @api, html: {class: 'form-horizontal'} do |f| %>
    <% if @api.errors.any? %>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10 alert alert-danger" role="alert">
            <h4>
              <%= pluralize(@api.errors.count, "error") %> prohibited
              this article from being saved:
            </h4>
            <ul>
              <% @api.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, autofocus: true, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Save", class: 'btn btn-default' %>
      </div>
    </div>
<% end %>

app/views/apis/edit.html.erb
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <h2>Edit API</h2>
  </div>
</div>

<%= render 'form' %>

app/views/apis/event.html.erb
<h4>Information about event</h4>

<table class="table">
  <thead>
  <tr>
    <th>Data</th>
    <th>Source</th>
    <th>Value</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Method</td>
    <td><code>static</code></td>
    <td>
      <pre><%= @event.method %></pre>
    </td>
  </tr>
  <tr>
    <td>Body</td>
    <td><code>static</code></td>
    <td>
      <pre><%= @event.body %></pre>
    </td>
  </tr>
  <% @event.properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><code><%= property.source %></code></td>
        <td>
          <pre><%= property.value %></pre>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/apis/index.html.erb
<h1>All APIs</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @apis.each do |api| %>
      <tr>
        <td><%= api.name %></td>
        <td>
          <div class="btn-group btn-group-xs" role="group">
            <%= link_to 'Show', api_path(api), class: 'btn btn-default', role: 'button' %>
            <%= link_to 'Edit', edit_api_path(api), class: 'btn btn-default', role: 'button' %>
            <%= link_to 'Destroy', api_path(api), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default', role: 'button' %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/apis/new.html.erb
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <h2>New API</h2>
  </div>
</div>

<%= render 'form' %>

app/views/apis/show.html.erb
<h4>Information about API handler</h4>

<table class="table">
  <thead>
  <tr>
    <th>Property</th>
    <th>Value</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Name</td>
    <td><%= @api.name %></td>
  </tr>
  <tr>
    <td>UUID</td>
    <td><%= @api.uuid %></td>
  </tr>
  <tr>
    <td>Last update</td>
    <td><%= @api.updated_at %></td>
  </tr>
</table>

<h4>Usage</h4>

<div class="alert alert-info" role="alert">
  <p>Example <code>GET</code> usage:
    <code>curl -X GET <%= request.protocol %><%= request.env['HTTP_HOST'] %>/api/<%= @api.uuid %></code></p>
  <p>Example <code>POST</code> usage:
    <code>curl -X POST -d "body" <%= request.protocol %><%= request.env['HTTP_HOST'] %>/api/<%= @api.uuid %></code></p>
</div>

<h4>Noticed events</h4>

<table class="table">
  <thead>
  <tr>
    <th>Id</th>
    <th>Date</th>
    <th>Method</th>
    <th>Params</th>
    <th>Body</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @api.events.each do |event| %>
      <tr>
        <td>#<%= event.id %></td>
        <td><%= event.created_at %></td>
        <td><code><%= event.method %></code></td>
        <td>
          <pre><%= event.params %></pre>
        </td>
        <td>
          <pre><%= event.body %></pre>
        </td>
        <td>
          <div class="btn-group btn-group-xs" role="group">
            <%= link_to 'Show', '/apis/%d/events/%d' % [@api.id, event.id], class: 'btn btn-default', role: 'button' %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yet Another API Server</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Yet Another API Server">
  <meta name="author" content="Paweł Suder <pawel@suder.info>">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
        integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu" type="text/css">

  <style>
    body {
      padding-top: 70px;
      font-family: "Ubuntu", sans-serif;
    }

    pre {
      overflow: auto;
      word-wrap: break-word;
      white-space: pre;
      max-width: 400px;
    }
  </style>

  <!-- Other scripts -->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</head>
<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Yet Another API Server</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">APIs
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All APIs", apis_path %></li>
            <li><%= link_to "New API", new_api_path %></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Current API actions</li>
            <% if defined? @api and not @api.new_record? %>
                <li><%= link_to "Edit", edit_api_path(@api) %></li>
                <li><%= link_to "Destroy", api_path(@api), method: :delete, data: {confirm: "Are you sure?"} %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
  <% end %>
  <% if alert %>
      <div class="alert alert-warning" role="alert"><%= alert %></div>
  <% end %>

  <%= yield %>
</div> <!-- /container -->

<!-- Sentry -->
<script src="https://browser.sentry-cdn.com/4.5.3/bundle.min.js" crossorigin="anonymous"></script>
<script>
(function() {
  Sentry.init({ dsn: 'https://53b8f0ddf2d94ac2b65dff12dc2754a8@sentry.io/1380399' });
})();
</script>

<!-- Latest compiled and minified JavaScript -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
        integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Yet Another API Server</h1>
  <p>It is a mock API server similar to <a href="//requestb.in">requestb.in</a> which can be self-hosted. Source code is
    hosted on <a href="//github.com/pasuder/mock-api-server">GitHub</a>.
  <p>
    <%= link_to 'Proceed with new API handler', new_api_path, class: 'btn btn-lg btn-primary', role: 'button' %>
  </p>
</div>